Enhanced UI of mark exit page according to design file
HackSlashNITP/Hostelite pull request #6
Opened 2023-10-13 06:14 UTC by ShubhamTiwari55

@RitwikSingh28 Sir the issue #4 has been resolved now. I have added blur effects to background image so that the page becomes more readable and adjusted elements by giving them proper padding and margin. Also I have added the hostelite image in the bottom as per the design file.
![WhatsApp Image 2023-10-13 at 11 40 57_f9ddcf71](https://github.com/HackSlashNITP/Hostelite/assets/125534462/446f2b7c-4eae-4816-93b8-264caaaaf430)

2023-10-14 05:41 UTC, RitwikSingh28 commented on lib/student_screens/mark_exit.dart
> +            constraints: BoxConstraints.expand(),
The background image should have some margin from the left-side of the screen.

2023-10-14 05:42 UTC, RitwikSingh28 requested changes
Please make the change specified in the comment.

2023-10-14 07:37 UTC, ShubhamTiwari55 commented
@RitwikSingh28 Sir the required change i.e adding left margin has been done. Kindly review the updated PR.
<img src="![WhatsApp Image 2023-10-14 at 13 03 13_08123499](https://github.com/HackSlashNITP/Hostelite/assets/125534462/c15bb350-2b0c-4f27-ae8a-26791f90acd1)" alt="alt text" width="200" height="200" />

2023-10-15 05:00 UTC, RitwikSingh28 approved these changes
Great work! :partying_face: 

Merging into `main` branch

2023-10-15 05:00 UTC, merged